# Generated by Django 5.0.7 on 2024-07-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toaso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ElectiveSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='core_subjects',
            field=models.ManyToManyField(to='toaso.coresubjects'),
        ),
        migrations.AddField(
            model_name='student',
            name='elective_subjects',
            field=models.ManyToManyField(to='toaso.electivesubjects'),
        ),
    ]
