# Generated by Django 5.0.7 on 2024-07-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toaso', '0002_coresubjects_electivesubjects_student_core_subjects_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElectiveSubjects',
            new_name='CoreSubject',
        ),
        migrations.RenameModel(
            old_name='CoreSubjects',
            new_name='ElectiveSubject',
        ),
    ]
