# Generated by Django 5.0.7 on 2024-07-27 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toaso', '0003_rename_electivesubjects_coresubject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SCIENCE', 'GENERAL SCIENCE'), ('BUSINESS', 'BUSINESS'), ('G.ARTS', 'GENERAL ARTS'), ('V.ARTS', 'VISUAL ARTS'), ('HOME_ECONS', 'HOME ECONOMICS')], max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='core_subjects',
            field=models.ManyToManyField(to='toaso.coresubject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='elective_subjects',
            field=models.ManyToManyField(to='toaso.electivesubject'),
        ),
        migrations.AddField(
            model_name='electivesubject',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elective_subjects', to='toaso.programs'),
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toaso.programs'),
        ),
    ]
