# Generated by Django 5.0.7 on 2024-07-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toaso', '0007_remove_student_core_subjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectiveSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cutt_off_point', models.IntegerField()),
                ('career', models.CharField(max_length=100)),
                ('note', models.TextField(null=True)),
                ('elective_subject', models.ManyToManyField(to='toaso.electivesubject')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('aggregate', models.IntegerField()),
                ('career_aspiration', models.CharField(max_length=100)),
                ('elective_subjects', models.ManyToManyField(to='toaso.electivesubject')),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
