# Generated by Django 5.0.7 on 2024-07-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toaso', '0011_alter_program_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
