# Generated by Django 5.0.7 on 2024-07-30 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toaso', '0014_remove_program_constant_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='elective_subject',
        ),
        migrations.AddField(
            model_name='program',
            name='constant_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constant_for_programs', to='toaso.electivesubject'),
        ),
        migrations.AddField(
            model_name='program',
            name='elective_requirement_logic',
            field=models.CharField(choices=[('ANY', 'Any'), ('ALL', 'All'), ('CONSTANT_PLUS_TWO', 'Constat plus Two')], default='ANY', max_length=50),
        ),
        migrations.AddField(
            model_name='program',
            name='elective_requirements',
            field=models.ManyToManyField(blank=True, related_name='required_for_programs', to='toaso.electivesubject'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='elective_subjects',
            field=models.ManyToManyField(related_name='users', to='toaso.electivesubject'),
        ),
    ]
