# Generated by Django 5.0.7 on 2024-08-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toaso', '0015_remove_program_elective_subject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='cutt_off_point',
            new_name='cut_off_point',
        ),
    ]
