# Generated by Django 5.0.7 on 2024-08-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toaso', '0018_school_program_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='required_interests',
            field=models.ManyToManyField(blank=True, null=True, related_name='programs', to='toaso.interest'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='toaso.interest'),
        ),
    ]
