# Generated by Django 5.0.7 on 2024-08-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toaso', '0019_interest_program_required_interests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='cut_off_point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
