# Generated by Django 5.0.7 on 2024-08-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toaso', '0019_interest_program_required_interests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='required_interests',
            field=models.ManyToManyField(related_name='programs', to='toaso.interest'),
        ),
    ]
