# Generated by Django 5.0.7 on 2024-08-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toaso', '0020_alter_program_required_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(related_name='users', to='toaso.interest'),
        ),
    ]
