# Generated by Django 5.0.7 on 2024-09-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toaso', '0021_alter_userprofile_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
