# Generated by Django 5.0.7 on 2024-09-29 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toaso', '0023_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='industry_insights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='required_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='sucess_steps',
            field=models.TextField(blank=True, null=True),
        ),
    ]
